import numpy as np

# GPS Arb (arbitrary point-wise) spectrum constraints — both are HARD:
#   1. Energy points must be in STRICTLY INCREASING order.
#   2. At most 1024 points. G4SPSEneDistribution::LinearInterpolation uses a
#      1024-element buffer; more points overrun it and abort the run with a
#      stack-smashing SIGABRT.
MAX_ARB_POINTS = 1024

# Load data
data = np.loadtxt('spectrum.txt')
wavelength = data[:, 0]  # nm
counts = data[:, 1]

# Convert wavelength to energy. 1239.841939 eV*nm / lambda[nm] = energy[eV];
# it is written below with an explicit 'e-6' suffix so the value lands in MeV,
# the Geant4 default unit for /gps/hist/point.
energy = 1239.841939 / wavelength  # eV

# Adjust negative values to zero
counts_adjusted = np.maximum(counts, 0)

# Normalize
peak = np.max(counts_adjusted)
normalized_counts = counts_adjusted / peak if peak > 0 else counts_adjusted

# GPS requires strictly increasing energy (i.e. decreasing wavelength).
order = np.argsort(energy)
energy = energy[order]
normalized_counts = normalized_counts[order]

# Drop duplicate energies (a zero-width segment breaks linear interpolation).
keep = np.concatenate(([True], np.diff(energy) > 0))
energy = energy[keep]
normalized_counts = normalized_counts[keep]

# Enforce the 1024-point cap by evenly downsampling, always keeping the
# endpoints so the spectral range is preserved.
if len(energy) > MAX_ARB_POINTS:
    idx = np.unique(np.linspace(0, len(energy) - 1, MAX_ARB_POINTS).round().astype(int))
    energy = energy[idx]
    normalized_counts = normalized_counts[idx]

# Create Geant4 macro. Particle type is intentionally NOT set here so the
# caller (e.g. run_285.mac -> /gps/particle opticalphoton) controls it.
with open('../mac/spectrum_macro.mac', 'w') as f:
    f.write('# Generated by input/create_macro.py from input/spectrum.txt.\n')
    f.write('# Energies in MeV (eV value x 1e-6); strictly increasing; <= 1024 points.\n')
    f.write('/gps/ene/type Arb\n')
    f.write('/gps/hist/type arb\n')

    # Write all data points (increasing energy)
    for e, p in zip(energy, normalized_counts):
        f.write(f'/gps/hist/point {e:.6f}e-6 {p:.6f}\n')

    f.write('/gps/hist/inter Lin\n')

# energy[] is in eV; the macro writes it as MeV via the 'e-6' suffix.
print(f'Wrote ../mac/spectrum_macro.mac: {len(energy)} points, '
      f'E {energy[0]:.4f}..{energy[-1]:.4f} eV '
      f'(lambda {1239.841939 / energy[-1]:.1f}..'
      f'{1239.841939 / energy[0]:.1f} nm)')
