/vis/open OGL
/vis/viewer/set/viewpointVector -1 0 0
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate

# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit

# Camera menu:
/gui/addMenu camera Camera
/gui/addButton camera "Front" "/vis/viewer/set/viewpointVector 0 0 1"
/gui/addButton camera "Side"  "/vis/viewer/set/viewpointVector -1 0 0"
/gui/addButton camera "Top"   "/vis/viewer/set/viewpointVector 0 -1 0"
/gui/addButton camera "Reset"   "/vis/viewer/set/viewpointVector -1 1 1"

# Run menu :
/gui/addMenu run Run
/gui/addButton run "Particle e-" "/gps/particle e-"
/gui/addButton run "Energy 0.1 MeV" "/gps/energy 0.1 MeV"
/gui/addButton run "beamOn 1" "/run/beamOn 1"
