#include "run.hh"

MyRunAction::MyRunAction()
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  man->CreateNtuple("Photons", "Photons");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->FinishNtuple(0);

  man->CreateNtuple("Hits", "Hits");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->FinishNtuple(1);

  man->CreateNtuple("Energy", "Energy");
  man->CreateNtupleDColumn("fEdep");
  man->FinishNtuple(2);


  // Primary particle information:
  man->CreateNtuple("Primary", "Primary Particle Information");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("posX"); // position
  man->CreateNtupleDColumn("posY");
  man->CreateNtupleDColumn("posZ");
  man->CreateNtupleDColumn("momX"); // momentum
  man->CreateNtupleDColumn("momY");
  man->CreateNtupleDColumn("momZ"); 
  man->CreateNtupleDColumn("wl"); // wavelength
  man->CreateNtupleIColumn("pdg"); // pdg code
  man->FinishNtuple(3);

  // optical photons generated by WLS process
  man->CreateNtuple("WLSPhoton", "Optical Photons from WLS");
  man->CreateNtupleIColumn("eventID");        // Event identifier
  man->CreateNtupleDColumn("posX");           // Emission position X
  man->CreateNtupleDColumn("posY");           // Emission position Y
  man->CreateNtupleDColumn("posZ");           // Emission position Z
  man->CreateNtupleDColumn("cosTheta");      // zenith angle
  man->CreateNtupleDColumn("phi");      // azimuth angle
  man->CreateNtupleIColumn("processName");      // WLS or Scintillation
  man->CreateNtupleDColumn("t");     // Global time of emission
  man->CreateNtupleIColumn("pdg");          // PDG code of the photon (typically 22 for optical photons)
  man->CreateNtupleDColumn("wl"); // wavelength
  man->CreateNtupleIColumn("matName");          // material name
  man->FinishNtuple(4);

  // Primary photon properties for optical validation (Fresnel, reflection)
  man->CreateNtuple("OpticalValidation", "Optical Properties Validation");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("wavelength");
  man->CreateNtupleDColumn("incidentAngle");
  man->CreateNtupleSColumn("material");
  man->CreateNtupleIColumn("reflected");  // 1 if reflected (finalZ < source plane), 0 if transmitted
  man->CreateNtupleDColumn("posX");
  man->CreateNtupleDColumn("posY");
  man->CreateNtupleDColumn("posZ");
  man->FinishNtuple(5);

  // Validation detector: photons leaking through the Vikuiti backplane
  man->CreateNtuple("BackplaneLeak", "Photons leaking through Vikuiti backplane");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->FinishNtuple(6);

  // Ntuple 7 (EdgeStrip) removed: the ±x edges of the blue WLS slab are now
  // covered by Vikuiti foils (lateral reflectors), not open validation detectors.
}

MyRunAction::~MyRunAction()
{}

void MyRunAction::BeginOfRunAction(const G4Run* run)
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  G4int runNumber = run->GetRunID();
  std::stringstream strRunID;
  strRunID << runNumber;
  man->OpenFile("output_apexltsim"+strRunID.str()+".root");

}

void MyRunAction::EndOfRunAction(const G4Run*)
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  man->Write();
  man->CloseFile();
}
