#include "run.hh"

MyRunAction::MyRunAction()
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  // ── Ntuple ID → detector-region map (two-layer light trap) ──────────────────
  //   0  SiPMPhotons        — every photon reaching a SiPM face (pre-PDE), 2nd-layer edges
  //   1  SiPMHits           — SecondLayerEdges: photons collected/detected by the SiPMs (post-PDE)
  //   2  Energy             — deposited energy
  //   3  Primary            — (a) primary particle info
  //   4  WLSPhoton          — WLS/scintillation photon births
  //   5  OpticalValidation  — Fresnel/reflection validation
  //   6  SecondLayerBackplane — (d) leak through the Vikuiti backplane foil
  //   7  FirstLayerBackplane  — (b) photons crossing the first-layer back (+z) face
  //   8  FirstLayerEdges      — (c) photons reaching the first-layer ±x edges
  // Ntuples 6/7/8 share MyLeakDetector's fill and carry a 'forward' int column
  // (index 7): 1 if mom.z()>0 (forward, out of layer 1), else 0 (e.g. Vikuiti-
  // reflected light travelling back -z). Both directions are recorded.
  // Regions a/d/e reuse existing ntuples (Primary, SecondLayerBackplane, SiPMHits).
  // The SiPM trees are read by name in analysis/analyze_efficiency.py.

  man->CreateNtuple("SiPMPhotons", "Photons reaching a SiPM face (pre-PDE)");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->FinishNtuple(0);

  man->CreateNtuple("SiPMHits", "Photons collected/detected by the SiPMs (post-PDE)");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->FinishNtuple(1);

  man->CreateNtuple("Energy", "Energy");
  man->CreateNtupleDColumn("fEdep");
  man->FinishNtuple(2);


  // Primary particle information:
  man->CreateNtuple("Primary", "Primary Particle Information");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("posX"); // position
  man->CreateNtupleDColumn("posY");
  man->CreateNtupleDColumn("posZ");
  man->CreateNtupleDColumn("momX"); // momentum
  man->CreateNtupleDColumn("momY");
  man->CreateNtupleDColumn("momZ"); 
  man->CreateNtupleDColumn("wl"); // wavelength
  man->CreateNtupleIColumn("pdg"); // pdg code
  man->FinishNtuple(3);

  // optical photons generated by WLS process
  man->CreateNtuple("WLSPhoton", "Optical Photons from WLS");
  man->CreateNtupleIColumn("eventID");        // Event identifier
  man->CreateNtupleDColumn("posX");           // Emission position X
  man->CreateNtupleDColumn("posY");           // Emission position Y
  man->CreateNtupleDColumn("posZ");           // Emission position Z
  man->CreateNtupleDColumn("cosTheta");      // zenith angle
  man->CreateNtupleDColumn("phi");      // azimuth angle
  man->CreateNtupleIColumn("processName");      // WLS or Scintillation
  man->CreateNtupleDColumn("t");     // Global time of emission
  man->CreateNtupleIColumn("pdg");          // PDG code of the photon (typically 22 for optical photons)
  man->CreateNtupleDColumn("wl"); // wavelength
  man->CreateNtupleIColumn("matName");          // material name
  man->FinishNtuple(4);

  // Primary photon properties for optical validation (Fresnel, reflection)
  man->CreateNtuple("OpticalValidation", "Optical Properties Validation");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("wavelength");
  man->CreateNtupleDColumn("incidentAngle");
  man->CreateNtupleSColumn("material");
  man->CreateNtupleIColumn("reflected");  // 1 if reflected (finalZ < source plane), 0 if transmitted
  man->CreateNtupleDColumn("posX");
  man->CreateNtupleDColumn("posY");
  man->CreateNtupleDColumn("posZ");
  man->FinishNtuple(5);

  // (d) SecondLayerBackplane: photons leaking through the Vikuiti backplane foil
  // behind the blue WLS slab (~2 % of those hitting it).  Terminal counter.
  man->CreateNtuple("SecondLayerBackplane", "Photons leaking through Vikuiti backplane");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->CreateNtupleDColumn("fcosTheta");   // momentum-z direction cosine
  man->CreateNtupleIColumn("forward");     // 1 if mom.z()>0 (forward), else 0
  man->FinishNtuple(6);

  // (b) FirstLayerBackplane: photons crossing the back (+z) face of the first
  // layer (pTP/UV-acrylic stack) into the LAr gap.  Pass-through counter — the
  // photon continues to the blue slab — so only photons that escape first-layer
  // TIR are counted.  Pairs with WLSPhoton (birth) for first-layer collection.
  man->CreateNtuple("FirstLayerBackplane", "Photons crossing the first-layer back face");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->CreateNtupleDColumn("fcosTheta");   // >0 = forward into gap toward blue slab
  man->CreateNtupleIColumn("forward");     // 1 if mom.z()>0 (forward), else 0
  man->FinishNtuple(7);

  // (c) FirstLayerEdges: photons reaching the ±x edges of the first layer.
  // Pass-through counter — records lateral escape from the first-layer stack.
  man->CreateNtuple("FirstLayerEdges", "Photons reaching the first-layer +/-x edges");
  man->CreateNtupleIColumn("eventID");
  man->CreateNtupleDColumn("fX");
  man->CreateNtupleDColumn("fY");
  man->CreateNtupleDColumn("fZ");
  man->CreateNtupleDColumn("fT");
  man->CreateNtupleDColumn("fwl");
  man->CreateNtupleDColumn("fcosTheta");   // momentum-z direction cosine
  man->CreateNtupleIColumn("forward");     // 1 if mom.z()>0 (forward), else 0
  man->FinishNtuple(8);
}

MyRunAction::~MyRunAction()
{}

void MyRunAction::BeginOfRunAction(const G4Run* run)
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  G4int runNumber = run->GetRunID();
  std::stringstream strRunID;
  strRunID << runNumber;
  man->OpenFile("output_apexltsim"+strRunID.str()+".root");

}

void MyRunAction::EndOfRunAction(const G4Run*)
{
  G4AnalysisManager *man = G4AnalysisManager::Instance();

  man->Write();
  man->CloseFile();
}
